return {
  -- {
  --   'folke/snacks.nvim',
  --   priority = 1000,
  --   lazy = false,
  --   ---@type snacks.Config
  --   opts = {
  --     bigfile = { enabled = true },
  --     dashboard = { enabled = true },
  --     explorer = { enabled = false },
  --     indent = { enabled = false },
  --     input = { enabled = false },
  --     picker = { enabled = true },
  --     notifier = { enabled = false },
  --     quickfile = { enabled = true },
  --     scope = { enabled = false },
  --     scroll = { enabled = false },
  --     statuscolumn = { enabled = false },
  --     words = { enabled = false },
  --   },
  -- },
}
